### ISSUE TITLE
Feat.req. Win build 

### ISSUE THREAD

**Issue by necros2k7** [HenadziMatuts/Reuromancer#8]

**Comment by HenadziMatuts** [comment]
What do you actually mean?

**Comment by necros2k7** [comment]
can you compile binary exe to run in Windows and post it to Releases section?

**Comment by HenadziMatuts** [comment]
Current version is too raw so I don't want to post it as Release. I can send it to you via e-mail if you provide me an address.

**Comment by necros2k7** [comment]
It would be great) vladislav2k4 at mail.ru

**Comment by HenadziMatuts** [comment]
Sent.

**Comment by sergeevabc** [comment]
Может быть, пора скомпилировать ```.exe``` для не-разработчиков?
